version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    container_name: zookeeper_demo
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    container_name: kafka_demo
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9991
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  connect:
    image: quay.io/debezium/connect:1.9
    container_name: debezium_demo
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      CONNECT_PLUGIN_PATH: /kafka/connect
    volumes:
      - ./connect-plugins:/kafka/connect

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql_dvt
      MYSQL_USER: dovanthien
      MYSQL_PASSWORD: 210404
      MYSQL_DATABASE: e_commerce
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data_sources:/tmp/data
      - ./load_dataset_into_mysql:/tmp/load/dataset
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

  postgres:
    image: postgres:15
    container_name: postgres_dw
    environment:
      POSTGRES_USER: dovanthien
      POSTGRES_PASSWORD: 210404
      POSTGRES_DB: E_COMMERCE # Đây là DW của bạn
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- THÊM METABASE ---
  # metabase:
  #   image: metabase/metabase:latest
  #   container_name: metabase
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - MB_DB_TYPE=postgres
  #     - MB_DB_DBNAME=metabase_db
  #     - MB_DB_PORT=5432
  #     - MB_DB_USER=dovanthien
  #     - MB_DB_PASS=210404
  #     - MB_DB_HOST=postgres # Kết nối nội bộ Docker tới service postgres
  #   depends_on:
  #     - postgres
  #   restart: always

  # --- THÊM AIRFLOW (Webserver & Scheduler) ---
  airflow-webserver:
    image: apache/airflow:2.7.1-python3.10
    container_name: airflow_webserver
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://dovanthien:210404@postgres:5432/airflow_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=super-secret-key-123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./checkpoints:/opt/airflow/checkpoints
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.7.1-python3.10
    container_name: airflow_scheduler
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://dovanthien:210404@postgres:5432/airflow_db
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__WEBSERVER__SECRET_KEY=super-secret-key-123
    volumes:
      - ./dags:/opt/airflow/dags
      - ./checkpoints:/opt/airflow/checkpoints
    command: scheduler

volumes:
  postgres_data: